### ISSUE TITLE
Greeting from the Po river

### ISSUE THREAD

**Issue by AlexSartori** [notfilippo/karmacount#1]
![enzomma](https://user-images.githubusercontent.com/9355579/199958936-ce3d6cbc-5a73-4e58-a3a9-17225c9b667a.GIF)

**Comment by notfilippo** [comment]
> Open source moment

https://user-images.githubusercontent.com/12383260/203658485-1a532e4f-0414-42eb-89b3-f8c6eae034f7.mov

> Open source moment
